### PR TITLE
Initialize variables, add override_freq_hz

### PR DESCRIPTION
**Pull request by FurTrader**
override_freq_hz was added in ESP-IDF 5.5.0, and passing uninitialized garbage to it causes the SPI clock to peg at the APB clock frequency

This resolves issue #19

### CODE REVIEW

**Comment by mkfrey** [comment]
I'm also a bit concerned about the use of the emtpy initializer `{}`. This seems to a new feature of C23, but according to the ESP-IDF docs even the newest 5.5.0 is using a GNU dialect of C17.

Does this even compile with older versions of the ESP-IDF?

**Comment by FurTrader** [comment]
It does compile with ESP_IDF 5.5.0 and 5.1.4, but I agree, it should be {0}.

The conditional is still needed because the member `override_freq_hz doesnt` exist prior to 5.5.0, so I get an error compiling with 5.1.4:
```
src/u8g2_esp32_hal.c:96:43: error: 'spi_transaction_t' has no member named 'override_freq_hz'
```

I removed the memset from line 53.

I pushed these changes to my fork.

**Comment by mkfrey** [comment]
What I meant was that you don't even need to set `override_freq_hz` to zero at all, since it will already be zero initialized.

**Comment by mkfrey** [comment]
I get you, the struct should have been completely zero initialized to avoid this issue in the first place. I'm fine with using a comment to signal that this field exists from 5.5.0.
